import Head from 'next/head'
import Layout from '../components/Layout'
import Link from 'next/link'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.center}>
          <h1 className={inter.className}> Welcome to my e-learning center </h1>
        </div>

        <div className={styles.grid}>
          <Link href="/learn/next" className={styles.card}>
            <h2 className={inter.className}>
              Next <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </Link>

          <Link href="/learn/react" className={styles.card}>
            <h2 className={inter.className}>
              React <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about React.js features and&nbsp;API.
            </p>
          </Link>

          <Link href="/learn/vue" className={styles.card}>
            <h2 className={inter.className}>
              Vue <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Vue.js features and&nbsp;API.
            </p>
          </Link>

          <Link href="/learn/angular" className={styles.card}>
            <h2 className={inter.className}>
              Angular <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Angular.js features and&nbsp;API.
            </p>
          </Link>
        </div>
      </main>
    </Layout>
  )
}
